global:
  environment: dev
frontend:
  namespace: frontend
  image:
    repository: 826136930409.dkr.ecr.ap-south-1.amazonaws.com/assignment-frontend
    tag: de4877b42e69c540ed3c62a7d2c3d6c0cce32caf
  replicaCount: 1
  service:
    port: 80
  hpa:
    enabled: true
    min: 1
    max: 2
    memory: 70
  ingress:
    enabled: false
    host: ui.example.com
    scheme: internet-facing
    group: app-platform
backend:
  namespace: backend
  image:
    repository: 826136930409.dkr.ecr.ap-south-1.amazonaws.com/assignment-backend
    tag: de4877b42e69c540ed3c62a7d2c3d6c0cce32caf
  replicaCount: 1
  service:
    port: 8000
  hpa:
    enabled: true
    min: 1
    max: 2
    memory: 70
  ingress:
    enabled: false
    host: ui.example.com
    scheme: internet-facing
    group: app-platform
