name: CI-CD Pipeline

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 826136930409.dkr.ecr.ap-south-1.amazonaws.com
  ECR_BACKEND_REPO: assignment-backend
  ECR_FRONTEND_REPO: assignment-frontend
  EKS_CLUSTER_NAME: assignment-cluster
  VITE_API_URL: http://assignment-api.jay.cloud-ip.cc
  IMAGE_TAG: ${{ github.sha }}

jobs:

  ci:
    name: ci-jobs
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::826136930409:role/GitHubAction-AssumeRoleWithAction
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push backend image
        working-directory: application/backend
        run: |
          docker build -t $ECR_BACKEND_REPO:${IMAGE_TAG} .
          docker tag $ECR_BACKEND_REPO:${IMAGE_TAG} \
            ${{ steps.ecr.outputs.registry }}/$ECR_BACKEND_REPO:latest
          docker tag $ECR_BACKEND_REPO:${IMAGE_TAG} \
            ${{ steps.ecr.outputs.registry }}/$ECR_BACKEND_REPO:${IMAGE_TAG}
          docker push ${{ steps.ecr.outputs.registry }}/$ECR_BACKEND_REPO:${IMAGE_TAG}
          docker push ${{ steps.ecr.outputs.registry }}/$ECR_BACKEND_REPO:latest 

      - name: Build & push frontend image
        working-directory: application/frontend
        run: |
          docker build \
            --build-arg VITE_API_URL=${VITE_API_URL} \
            -t $ECR_FRONTEND_REPO:${IMAGE_TAG} .
          docker tag $ECR_FRONTEND_REPO:${IMAGE_TAG} \
            ${{ steps.ecr.outputs.registry }}/$ECR_FRONTEND_REPO:${IMAGE_TAG}
          docker tag $ECR_FRONTEND_REPO:${IMAGE_TAG} \
            ${{ steps.ecr.outputs.registry }}/$ECR_FRONTEND_REPO:latest
          docker push ${{ steps.ecr.outputs.registry }}/$ECR_FRONTEND_REPO:${IMAGE_TAG}
          docker push ${{ steps.ecr.outputs.registry }}/$ECR_FRONTEND_REPO:latest